#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vi="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
    alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
    bc="bc -ql" \
    cp="cp -iv" \
    ffmpeg="ffmpeg -hide_banner" \
    mkd="mkdir -pv" \
    mv="mv -iv" \
    yt="youtube-dl --add-metadata -i" \
    yta="yt -x -f bestaudio/best";

# Colorize commands when possible.
alias \
    ccat="highlight --out-format=ansi" \
    diff="diff -Npur --color=auto" \
    grep="grep --color=auto" \
    ip="ip -color=auto" \
    ;

# Overide command
alias \
  history="history 0"\
  lf="lfub";

# These common commands are just too long! Abbreviate them.
alias \
    ka="killall" \
    trem="transmission-remote" \
    e="$EDITOR" \
    e.="$EDITOR ./" \
    v="$FILE_MANAGER ./ " \
    p="pacman" \
    g="git" \
    t="tig" \
    z="zathura";

alias -g \
    C='| xcopy' \
    V='| nvim -R -' \
    G='| grep' \
    H='| head' \
    L='| less -R' \
    T='| tail' \

alias \
    ..='cd ../' \
    ...='cd ../../' \
    ....='cd ../../../';

if [[ "$OSTYPE" == "darwin"* ]]; then
    alias ls="ls -G";
fi

if [[ "$OSTYPE" == "linux"* ]]; then
    alias rm="rm -vI --preserve-root";
    alias ls="ls -hN --color=auto --group-directories-first"
    alias ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc";
    alias weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport";
    alias xcopy='xclip -selection clipboard';
    alias xpaste='xclip -selection clipboard -o';
fi

