#!/bin/sh

RELATED_LINK=`
rg "\[\[$1\]\]" \
| rg -v "related link" \
| rg "\.md" \
| sed 's/\.md.*//' \
| sed 's/^/[[/' \
| sed 's/$/]]/' \
| sed 'N;s/\n/, /'`

sed -i "" "s|^related link.*|related link : $RELATED_LINK|" "$2"
