#!/bin/sh

RELATED_LINK=`
rg "\[\[$1\]\]" \
| rg -v "related link" \
| rg "\.md" \
| sed 's/\.md.*//' \
| sed 's/^/[[/' \
| sed 's/$/]]/' \
| xargs \
| sed -e 's/ /, /g'`

sed -i "" "s|^related link.*|related link : $RELATED_LINK|" "$2"
