#!/bin/bash

DOT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles"
DOT_CONFIG_DIR="$DOT_DIR/config"
DOT_LOCAL_DIR="$DOT_DIR/local"

[ ! -d "$HOME"/.local/bin ] && mkdir -p "$HOME"/.local/bin
[ ! -d "$HOME"/.local/script ] && mkdir -p "$HOME"/.local/script

ln -sf "$DOT_LOCAL_DIR"/bin/* "$HOME"/.local/bin
ln -sf "$DOT_LOCAL_DIR"/script/* "$HOME"/.local/script

[ -d "$HOME"/Pictures ] && cp -Rn  "$DOT_DIR"/Pictures/* "${XDG_PICTURES_DIR:-$HOME/Pictures}"

ln -sf "$DOT_CONFIG_DIR"/zsh/zprofile "$HOME"/.zprofile

[ ! -d "${XDG_CONFIG_HOME:-$HOME/.config}"/zsh ] && mkdir "${XDG_CONFIG_HOME:-$HOME/.config}"/zsh
ln -sf "$DOT_CONFIG_DIR"/zsh/zshrc "${XDG_CONFIG_HOME:-$HOME/.config}"/zsh/.zshrc

[ ! -d "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim ] && mkdir "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim
ln -sf "$DOT_CONFIG_DIR"/nvim/init.vim "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim/init.vim
ln -sf "$DOT_CONFIG_DIR"/nvim/coc-settings.json "${XDG_CONFIG_HOME:-$HOME/.config}"/nvim/coc-settings.json

[ ! -d "${XDG_CONFIG_HOME:-$HOME/.config}"/git ] && mkdir "${XDG_CONFIG_HOME:-$HOME/.config}"/git
ln -sf "$DOT_CONFIG_DIR"/git/config "${XDG_CONFIG_HOME:-$HOME/.config}"/git/config

[ ! -d "${XDG_CONFIG_HOME:-$HOME/.config}"/pet ] && mkdir "${XDG_CONFIG_HOME:-$HOME/.config}"/pet
ln -sf "$DOT_CONFIG_DIR"/pet/config.toml "${XDG_CONFIG_HOME:-$HOME/.config}"/pet/config.toml

[ ! -d "${XDG_DATA_HOME:-$HOME/.local/share}"/tig ] && mkdir "${XDG_DATA_HOME:-$HOME/.local/share}"/tig
[ ! -f "${XDG_DATA_HOME:-$HOME/.local/share}"/tig/history ] && touch "${XDG_DATA_HOME:-$HOME/.local/share}"/tig/history
[ ! -d "${XDG_CONFIG_HOME:-$HOME/.config}"/tig ] && mkdir "${XDG_CONFIG_HOME:-$HOME/.config}"/tig
ln -sf "$DOT_CONFIG_DIR"/tig/config "${XDG_CONFIG_HOME:-$HOME/.config}"/tig/config

[ ! -d "${XDG_CONFIG_HOME:-$HOME/.config}"/tmux ] && mkdir "${XDG_CONFIG_HOME:-$HOME/.config}"/tmux
ln -sf "$DOT_CONFIG_DIR"/tmux/tmux.conf "${XDG_CONFIG_HOME:-$HOME/.config}"/tmux/tmux.conf

[ ! -d "${XDG_CONFIG_HOME:-$HOME/.config}"/zathura ] && mkdir "${XDG_CONFIG_HOME:-$HOME/.config}"/zathura
ln -sf "$DOT_CONFIG_DIR"/zathura/zathurarc "${XDG_CONFIG_HOME:-$HOME/.config}"/zathura/zathurarc

[ ! -d ${XDG_CONFIG_HOME:-$HOME/.config}/vifm ] && mkdir ${XDG_CONFIG_HOME:-$HOME/.config}/vifm
[ -d ${XDG_CONFIG_HOME:-$HOME/.config}/vifm ] && ln -sf $DOT_CONFIG_DIR/vifm/vifmrc ${XDG_CONFIG_HOME:-$HOME/.config}/vifm/vifmrc

[ ! -d ${XDG_CONFIG_HOME:-$HOME/.config}/vifm/colors ] && mkdir ${XDG_CONFIG_HOME:-$HOME/.config}/vifm/colors
[ -d ${XDG_CONFIG_HOME:-$HOME/.config}/vifm/colors ] && ln -sf $DOT_CONFIG_DIR/vifm/colors/gruvbox.vifm ${XDG_CONFIG_HOME:-$HOME/.config}/vifm/colors/gruvbox.vifm

ln -sf "$DOT_LOCAL_DIR"/bin/* "$HOME"/.local/bin

if [[ "$OSTYPE" == "linux"* ]]; then
    [ ! -d "${XDG_CONFIG_HOME:-$HOME/.config}"/fontconfig ] && mkdir "${XDG_CONFIG_HOME:-$HOME/.config}"/fontconfig
    ln -sf "$DOT_CONFIG_DIR"/fontconfig/fonts.conf "${XDG_CONFIG_HOME:-$HOME/.config}"/fontconfig/fonts.conf

    [ ! -d "${XDG_CONFIG_HOME:-$HOME/.config}"/x11 ] && mkdir "${XDG_CONFIG_HOME:-$HOME/.config}"/x11
    ln -sf "$DOT_CONFIG_DIR"/x11/xinit "${XDG_CONFIG_HOME:-$HOME/.config}"/x11/xinitrc
    ln -sf "$DOT_CONFIG_DIR"/x11/xprofile "${XDG_CONFIG_HOME:-$HOME/.config}"/x11/xprofile
    ln -sf "$DOT_CONFIG_DIR"/x11/xresources "${XDG_CONFIG_HOME:-$HOME/.config}"/x11/xresources

    [ ! -d "${XDG_CONFIG_HOME:-$HOME/.config}"/youtube-dl ] && mkdir "${XDG_CONFIG_HOME:-$HOME/.config}"/youtube-dl
    ln -sf "$DOT_CONFIG_DIR"/youtube-dl/config "${XDG_CONFIG_HOME:-$HOME/.config}"/youtube-dl/config

    [ ! -d "${XDG_CONFIG_HOME:-$HOME/.config}"/calcurse ] && mkdir "${XDG_CONFIG_HOME:-$HOME/.config}"/calcurse
    ln -sf "$DOT_CONFIG_DIR"/calcurse/conf  "${XDG_CONFIG_HOME:-$HOME/.config}"/calcurse/conf

    [ ! -d "${XDG_CONFIG_HOME:-$HOME/.config}"/newsboat ] && mkdir "${XDG_CONFIG_HOME:-$HOME/.config}"/newsboat
    ln -sf "$DOT_CONFIG_DIR"/newsboat/config  "${XDG_CONFIG_HOME:-$HOME/.config}"/newsboat/config
    ln -sf "$DOT_CONFIG_DIR"/newsboat/urls  "${XDG_CONFIG_HOME:-$HOME/.config}"/newsboat/urls

    [ -d "$DOT_LOCAL_DIR"/bin-linux ]    && ln -sf "$DOT_LOCAL_DIR"/bin-linux/* "$HOME"/.local/bin
    [ -d "$DOT_LOCAL_DIR"/script-linux ] && ln -sf "$DOT_LOCAL_DIR"/script-linux/* "$HOME"/.local/script
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    [ ! -d ${XDG_CONFIG_HOME:-$HOME/.config}/ideavim ] && mkdir ${XDG_CONFIG_HOME:-$HOME/.config}/ideavim
    [ -d ${XDG_CONFIG_HOME:-$HOME/.config}/ideavim ] && ln -sf $DOT_CONFIG_DIR/ideavim/ideavimrc ${XDG_CONFIG_HOME:-$HOME/.config}/ideavim/ideavimrc

    [ -d "$DOT_LOCAL_DIR"/bin-mac ]    && ln -sf "$DOT_LOCAL_DIR"/bin-mac/* "$HOME"/.local/bin
    [ -d "$DOT_LOCAL_DIR"/script-mac ] && ln -sf "$DOT_LOCAL_DIR"/script-mac/* "$HOME"/.local/script
fi

